- job:
    name: testjob
    parent: base
    run: playbooks/testjob.yaml

- project:
    check:
      jobs:
        - testjob
    gate:
      jobs:
        - testjob
    post:
      jobs:
        - demo-job
    tag:
      jobs:
        - demo-job
